services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile to use for building the image.
    container_name: Finlyt
    ports:
      - 8080:8080
    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}  # Database URL.
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}  # Database username.
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}  # Database password.
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama:latest
    depends_on:
      db:
        condition: service_healthy
      ollamamodel:
        condition: service_completed_successfully
      ollama:
        condition: service_healthy
    networks:
     - finlyt_network
  db:
    image: mysql:8.0
    container_name: finlyt_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finlyt_network
  # Ollama service for running the Ollama model
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - finlyt_network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
  #ollama model service to pull the model
  ollamamodel:
    image: ollama/ollama:latest
    container_name: ollama_model
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    entrypoint: /bin/sh
    command: -c "ollama pull tinyllama"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - finlyt_network   

volumes:
  db-data:
  ollama-data:


networks:
  finlyt_network:
    driver: bridge
