apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"finlytargocd","namespace":"argocd"},"spec":{"destination":{"namespace":"finlyt","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"helm/finlyt","repoURL":"https://github.com/savitapadarya/Finlyt-GitOps.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2026-09-20T00:36:51Z"
  generation: 167
  name: finlytargocd
  namespace: argocd
  resourceVersion: "21219"
  uid: 9b9360a6-0c02-45ff-8ce5-33500bb6d86a
spec:
  destination:
    namespace: finlyt
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/finlyt
    repoURL: https://github.com/savitapadarya/Finlyt-GitOps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  conditions:
  - lastTransitionTime: "2026-09-20T03:43:02Z"
    message: 'Failed last sync attempt to [2bd0ae7a19839d9f0d5fe877a5252ae307427a2a]:
      one or more objects failed to apply (dry run) (retried 5 times).'
    type: SyncError
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-09-20T01:22:47Z"
    status: Degraded
  history:
  - deployStartedAt: "2026-09-20T01:22:34Z"
    deployedAt: "2026-09-20T01:22:46Z"
    id: 0
    initiatedBy:
      automated: true
    revision: f785c359078dde333038e064b78bb68bb84f6320
    source:
      path: helm/finlyt
      repoURL: https://github.com/savitapadarya/Finlyt-GitOps.git
      targetRevision: main
  operationState:
    finishedAt: "2026-09-20T03:43:00Z"
    message: one or more objects failed to apply (dry run) (retried 5 times).
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 2bd0ae7a19839d9f0d5fe877a5252ae307427a2a
        source:
          path: helm/finlyt
          repoURL: https://github.com/savitapadarya/Finlyt-GitOps.git
          targetRevision: main
        syncOptions:
        - CreateNamespace=true
    phase: Failed
    retryCount: 5
    startedAt: "2026-09-20T03:26:59Z"
    syncResult:
      resources:
      - group: apps
        hookPhase: Failed
        images:
        - savitapadarya/finlyt:e932848ed7c3efd06e8a6825b982a59a116a7563
        kind: Deployment
        message: |-
          creating patch with:
          original:
          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"finlytargocd:apps/Deployment:finlyt/finlyt-deployment"},"labels":{"app":"finlyt_frontend"},"name":"finlyt-deployment","namespace":"finlyt"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"finlyt_frontend"}},"template":{"metadata":{"labels":{"app":"finlyt_frontend"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"myconfigmap"}},{"secretRef":{"name":"secret-finlyt"}}],"image":"savitapadarya/finlyt:a2ad5d045ba87026f9e12e834486712d5142032b","imagePullPolicy":"IfNotPresent","imagePullSecrets":[{"name":"dockerhub-secret"}],"name":"finlyt-app","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"500m","memory":"768Mi"},"requests":{"cpu":"100m","memory":"256Mi"}}}],"initContainers":[{"command":["sh","-c","until nslookup db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 2; done"],"image":"busybox:1.36","name":"wait-for-database-service"},{"command":["sh","-c","until nslookup ollama-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for ollama; sleep 2; done"],"image":"busybox:1.36","name":"wait-for-ollama-service"}]}}}}

          modified:
          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"finlytargocd:apps/Deployment:finlyt/finlyt-deployment","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"argocd.argoproj.io/tracking-id\":\"finlytargocd:apps/Deployment:finlyt/finlyt-deployment\"},\"labels\":{\"app\":\"finlyt_frontend\"},\"name\":\"finlyt-deployment\",\"namespace\":\"finlyt\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"finlyt_frontend\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"finlyt_frontend\"}},\"spec\":{\"containers\":[{\"envFrom\":[{\"configMapRef\":{\"name\":\"myconfigmap\"}},{\"secretRef\":{\"name\":\"secret-finlyt\"}}],\"image\":\"savitapadarya/finlyt:e932848ed7c3efd06e8a6825b982a59a116a7563\",\"imagePullPolicy\":\"IfNotPresent\",\"imagePullSecrets\":[{\"name\":\"dockerhub-finlyt\"}],\"name\":\"finlyt-app\",\"ports\":[{\"containerPort\":8080}],\"resources\":{\"limits\":{\"cpu\":\"500m\",\"memory\":\"768Mi\"},\"requests\":{\"cpu\":\"100m\",\"memory\":\"256Mi\"}}}],\"initContainers\":[{\"command\":[\"sh\",\"-c\",\"until nslookup db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 2; done\"],\"image\":\"busybox:1.36\",\"name\":\"wait-for-database-service\"},{\"command\":[\"sh\",\"-c\",\"until nslookup ollama-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for ollama; sleep 2; done\"],\"image\":\"busybox:1.36\",\"name\":\"wait-for-ollama-service\"}]}}}}\n"},"labels":{"app":"finlyt_frontend"},"name":"finlyt-deployment","namespace":"finlyt"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"finlyt_frontend"}},"template":{"metadata":{"labels":{"app":"finlyt_frontend"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"myconfigmap"}},{"secretRef":{"name":"secret-finlyt"}}],"image":"savitapadarya/finlyt:e932848ed7c3efd06e8a6825b982a59a116a7563","imagePullPolicy":"IfNotPresent","imagePullSecrets":[{"name":"dockerhub-finlyt"}],"name":"finlyt-app","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"500m","memory":"768Mi"},"requests":{"cpu":"100m","memory":"256Mi"}}}],"initContainers":[{"command":["sh","-c","until nslookup db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 2; done"],"image":"busybox:1.36","name":"wait-for-database-service"},{"command":["sh","-c","until nslookup ollama-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for ollama; sleep 2; done"],"image":"busybox:1.36","name":"wait-for-ollama-service"}]}}}}

          current:
          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"finlytargocd:apps/Deployment:finlyt/finlyt-deployment","deployment.kubernetes.io/revision":"1","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"argocd.argoproj.io/tracking-id\":\"finlytargocd:apps/Deployment:finlyt/finlyt-deployment\"},\"labels\":{\"app\":\"finlyt_frontend\"},\"name\":\"finlyt-deployment\",\"namespace\":\"finlyt\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"finlyt_frontend\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"finlyt_frontend\"}},\"spec\":{\"containers\":[{\"envFrom\":[{\"configMapRef\":{\"name\":\"myconfigmap\"}},{\"secretRef\":{\"name\":\"secret-finlyt\"}}],\"image\":\"savitapadarya/finlyt:a2ad5d045ba87026f9e12e834486712d5142032b\",\"imagePullPolicy\":\"IfNotPresent\",\"imagePullSecrets\":[{\"name\":\"dockerhub-secret\"}],\"name\":\"finlyt-app\",\"ports\":[{\"containerPort\":8080}],\"resources\":{\"limits\":{\"cpu\":\"500m\",\"memory\":\"768Mi\"},\"requests\":{\"cpu\":\"100m\",\"memory\":\"256Mi\"}}}],\"initContainers\":[{\"command\":[\"sh\",\"-c\",\"until nslookup db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 2; done\"],\"image\":\"busybox:1.36\",\"name\":\"wait-for-database-service\"},{\"command\":[\"sh\",\"-c\",\"until nslookup ollama-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for ollama; sleep 2; done\"],\"image\":\"busybox:1.36\",\"name\":\"wait-for-ollama-service\"}]}}}}\n"},"creationTimestamp":"2026-09-20T01:22:44Z","generation":1,"labels":{"app":"finlyt_frontend"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:argocd.argoproj.io/tracking-id":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"finlyt-app\"}":{".":{},"f:envFrom":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8080,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:initContainers":{".":{},"k:{\"name\":\"wait-for-database-service\"}":{".":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}},"k:{\"name\":\"wait-for-ollama-service\"}":{".":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"argocd-controller","operation":"Update","time":"2026-09-20T01:22:44Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:terminatingReplicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","subresource":"status","time":"2026-09-20T03:30:19Z"}],"name":"finlyt-deployment","namespace":"finlyt","resourceVersion":"16849","uid":"f9eb7115-d37c-4c83-a6cd-4e307e92ace7"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"finlyt_frontend"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"finlyt_frontend"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"myconfigmap"}},{"secretRef":{"name":"secret-finlyt"}}],"image":"savitapadarya/finlyt:a2ad5d045ba87026f9e12e834486712d5142032b","imagePullPolicy":"IfNotPresent","name":"finlyt-app","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"768Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","initContainers":[{"command":["sh","-c","until nslookup db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 2; done"],"image":"busybox:1.36","imagePullPolicy":"IfNotPresent","name":"wait-for-database-service","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"command":["sh","-c","until nslookup ollama-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for ollama; sleep 2; done"],"image":"busybox:1.36","imagePullPolicy":"IfNotPresent","name":"wait-for-ollama-service","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2026-09-20T02:04:43Z","lastUpdateTime":"2026-09-20T02:04:43Z","message":"ReplicaSet \"finlyt-deployment-6f77575bb6\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2026-09-20T03:30:19Z","lastUpdateTime":"2026-09-20T03:30:19Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"terminatingReplicas":0,"updatedReplicas":1}}

          for: unable to find api field in struct Container for the json field "imagePullSecrets"
        name: finlyt-deployment
        namespace: finlyt
        status: SyncFailed
        syncPhase: Sync
        version: v1
      revision: 2bd0ae7a19839d9f0d5fe877a5252ae307427a2a
      source:
        path: helm/finlyt
        repoURL: https://github.com/savitapadarya/Finlyt-GitOps.git
        targetRevision: main
  reconciledAt: "2026-09-20T04:48:21Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: myconfigmap
    namespace: finlyt
    status: Synced
    version: v1
  - kind: Namespace
    name: finlyt
    status: Synced
    version: v1
  - kind: PersistentVolume
    name: db-pv-volume
    status: Synced
    version: v1
  - kind: PersistentVolume
    name: ollama-pv-volume
    status: Synced
    version: v1
  - kind: PersistentVolumeClaim
    name: db-pvc-claim
    namespace: finlyt
    status: Synced
    version: v1
  - kind: PersistentVolumeClaim
    name: ollama-pvc-claim
    namespace: finlyt
    status: Synced
    version: v1
  - kind: Secret
    name: secret-finlyt
    namespace: finlyt
    status: Synced
    version: v1
  - kind: Service
    name: app-service
    namespace: finlyt
    status: Synced
    version: v1
  - kind: Service
    name: db-service
    namespace: finlyt
    status: Synced
    version: v1
  - kind: Service
    name: ollama-service
    namespace: finlyt
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: finlyt-db-deployment
    namespace: finlyt
    status: OutOfSync
    version: v1
  - group: apps
    kind: Deployment
    name: finlyt-deployment
    namespace: finlyt
    status: OutOfSync
    version: v1
  - group: apps
    kind: Deployment
    name: finlyt-ollama-deployment
    namespace: finlyt
    status: OutOfSync
    version: v1
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    name: finlytargocd
    namespace: finlyt
    status: OutOfSync
    version: v2
  - group: networking.k8s.io
    kind: Ingress
    name: finlytargocd
    namespace: finlyt
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary:
    images:
    - busybox:1.36
    - mysql:8.0
    - ollama/ollama:latest
    - savitapadarya/finlyt:a2ad5d045ba87026f9e12e834486712d5142032b
  sync:
    comparedTo:
      destination:
        namespace: finlyt
        server: https://kubernetes.default.svc
      source:
        path: helm/finlyt
        repoURL: https://github.com/savitapadarya/Finlyt-GitOps.git
        targetRevision: main
    revision: 2bd0ae7a19839d9f0d5fe877a5252ae307427a2a
    status: OutOfSync
